Variabele1=("Simon")
Variabele2=("31")
Variabele3=("hobby is voetbal")
print("Value 1: "+Variabele1)
print("Value 2: "+Variabele2)
print("Value 3: "+Variabele3)

Variabele4=("Victor")
Variabele5=str(45)
Variabele6=("hobby; Wrakduiken")
print("Value 4: "+Variabele4)
print("Value 5: "+Variabele5)
print("Value 6: "+Variabele6)